name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "master" ]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Run a test
            run: | 
              pip install pytest
              pip install selenium
              pytest -s
